Support ComponentActivity
dropbox/kaiken pull request #35
Opened 2021-07-13 23:35 UTC by idunnololz

- Remove assumptions that the AuthAwareScopeOwnerActivity is a FragmentActivity so that Kaiken can work with compose

2021-07-13 23:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dropbox/kaiken?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dropbox/kaiken?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dropbox/kaiken?pullRequest=35) it.</sub>

2021-07-14 00:44 UTC, digitalbuddha commented
Lgtm. Please sign the cla as a formality, we are working on a better flow for internal folks.

Let's wait for Rodrigo to look as well

2021-07-14 16:36 UTC, rodgavila approved these changes
Looks good! Thanks for the change!

NIT: I might use `ComponentActivity` instead of the framework's Activity. Just because that will fail base in `finishIfInvalidAuth()` if the `Activity` does not implement `ViewModelStoreOwner`.

2021-07-14 17:23 UTC, rodgavila requested changes
Actually on second thought and after consulting with @rallat. Let's make it `ComponentActivity` instead of `Activity`. This gives us a little more leeway in the future. As a library we can always go to a less restrictive type, but not the opposite without potentially breaking clients. Thank you!

2021-07-14 23:33 UTC, rodgavila approved these changes
💯

2021-07-14 23:34 UTC, merged